//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hints()
        {
            this.SubPages = new HashSet<SubPages>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int LessonId { get; set; }
    
        public virtual Lessons Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubPages> SubPages { get; set; }
    }
}
