//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPages
    {
        public int id { get; set; }
        public int Url { get; set; }
        public Nullable<int> HintsId { get; set; }
    
        public virtual Hints Hints { get; set; }
    }
}
